[package]
name = "mappenstance2"
version = "0.1.0"
authors = ["Steven 'Steve' Kendall <skendall@neverware.com>"]
edition = "2018"

[lib]
name = "mapplib"
path = "src/mapplib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
